name: Run Shared Build and Push Workflow

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'Dockerfile'
      - '*.sh'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: foobar
    permissions:
      contents: read
      packages: write # required if push is true
    steps:
      - uses: jabez007/aws-kubectl/.github/shared/docker@master
        with:
          push: true
          tag: ${{ vars.AWS_REGION }}_${{ vars.EKS_CLUSTER }}
          build-args: |
            AWS_REGION=${{ vars.AWS_REGION }}
            EKS_CLUSTER=${{ vars.EKS_CLUSTER }}
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
