name: Run Shared Build Workflow

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    permissions:
      contents: read
    uses: jabez007/aws-kubectl/.github/workflows/shared.build_and_push.yml@master
    with:
      tag: ${{ vars.AWS_REGION }}_${{ vars.EKS_CLUSTER }}
      build-args: |
        AWS_REGION=${{ vars.AWS_REGION }}
        EKS_CLUSTER=${{ vars.EKS_CLUSTER }}
    secrets: inherit
