name: Test Shared Scripts

on:
  push:

jobs:
  test_delimited-string:
    runs-on: ubuntu-latest
    steps:

      - name: Test delimited-string for Docker tags
        id: docker-tags
        uses: jabez007/aws-kubectl/.github/shared/script/delimited-string@master
        with:
          source_string: ", dev , tst , prd"
          target_delimiter: " ghcr.io/foo-bar:"

      - name: Check delimited-string for Docker tags
        run: |
          echo "${{ steps.docker-tags.outputs.target_string }}"